# Generated by Django 3.1.1 on 2020-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='data_publicacao',
            field=models.DateField(),
        ),
    ]
